In [6]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import linear_model
import math

In [ ]:
df = pd.read_csv("homeprices2.csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
median_bedrooms = math.floor(df.bedrooms.median())


df.bedrooms.fillna(median_bedrooms, inplace=True)

In [9]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

print("Price of 3000 sqr ft, 3 bedrooms, 40 year old: ", reg.predict([[3000,3,40]])[0])
print("Price of 2500 sqr ft, 4 bedrooms, 5 year old: ", reg.predict([[2500,4,5]])[0])

Price of 3000 sqr ft, 3 bedrooms, 40 year old:  444399.9999999999
Price of 2500 sqr ft, 4 bedrooms, 5 year old:  588625.0